/**
 * Compiles content/posts/*.md into content/posts.generated.ts.
 *
 * Run `npm run posts` after adding or editing a file in content/posts/. The
 * output is committed; lib/repoPosts.test.ts fails if it has fallen behind
 * the Markdown, so a forgotten run shows up in the tests rather than as a
 * post that silently never appears.
 *
 * Why a generated module rather than reading the .md at runtime: the SPA,
 * the page function and the content API all need the posts, and a plain
 * import is the one thing all three can do the same way.
 *
 * Front matter is a deliberately small subset of YAML: one `key: value` per
 * line, where the value is a JSON string, array, number or boolean.
 */
import { readdir, readFile, writeFile } from 'node:fs/promises';
import { join } from 'node:path';
import { pathToFileURL } from 'node:url';

const DIR = 'content/posts';
const OUT = 'content/posts.generated.ts';

export const parsePost = (source, file) => {
  const match = /^---\r?\n([\s\S]*?)\r?\n---\r?\n([\s\S]*)$/.exec(source);
  if (!match) throw new Error(`${file}: missing front matter`);
  const meta = {};
  for (const line of match[1].split(/\r?\n/)) {
    if (!line.trim()) continue;
    const pair = /^([A-Za-z]+):\s*(.*)$/.exec(line);
    if (!pair) throw new Error(`${file}: cannot read front matter line "${line}"`);
    try {
      meta[pair[1]] = JSON.parse(pair[2]);
    } catch {
      throw new Error(`${file}: "${pair[1]}" must be a JSON value (quote strings)`);
    }
  }
  for (const key of ['title', 'slug', 'categoryId']) {
    if (typeof meta[key] !== 'string' || !meta[key].trim()) throw new Error(`${file}: "${key}" is required`);
  }
  return {
    id: `repo-${meta.slug}`,
    slug: meta.slug,
    title: meta.title,
    excerpt: meta.excerpt ?? '',
    content: match[2].replace(/\r\n/g, '\n').trim(),
    date: meta.date ?? '',
    readTime: meta.readTime ?? '',
    image: meta.image ?? '',
    author: meta.author ?? 'Ashim Kafle',
    tags: Array.isArray(meta.tags) ? meta.tags : [],
    // A post is a draft unless its file says otherwise.
    published: meta.published === true,
    seoTitle: meta.seoTitle ?? '',
    metaDescription: meta.metaDescription ?? '',
    ogImage: meta.ogImage ?? '',
    categoryId: meta.categoryId,
  };
};

export const compile = async () => {
  const files = (await readdir(DIR)).filter((file) => file.endsWith('.md')).sort();
  const posts = [];
  for (const file of files) {
    posts.push(parsePost(await readFile(join(DIR, file), 'utf8'), file));
  }
  const slugs = new Set();
  for (const post of posts) {
    if (slugs.has(post.slug)) throw new Error(`duplicate slug ${post.slug}`);
    slugs.add(post.slug);
  }
  return `// Generated by scripts/compile-posts.mjs from content/posts/*.md. Do not edit;
// edit the Markdown and run \`npm run posts\`.
import type { Blog } from '../types.js';

export const REPO_POSTS: Blog[] = ${JSON.stringify(posts, null, 2)};
`;
};

if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  const output = await compile();
  await writeFile(OUT, output, 'utf8');
  console.log(`compiled ${OUT}`);
}
